Repository SrigadaAkshayKumar/stock, pull requests merged in 2025-09, with the labels that each got.

#178 feat: add caching (Redis + in-memory fallback); fix sticky footer; ad…
  .github/PULL_REQUEST_TEMPLATE.md
  SETUP.md
  backend/airflow_dags/airflow/.env.example
  backend/requirements.txt
  backend/routes/stock_routes.py
  backend/tests/conftest.py
  backend/tests/test_cache_utils.py
  backend/tests/test_integration_cache.py
  backend/utils/__init__.py
  backend/utils/cache.py
  package.json
  src/App.css
  src/App.js
  src/components/About.jsx
  src/components/AuthContext.js
  src/components/BackToTopBtn.jsx
  src/components/ErrorBoundary.js
  src/components/Footer.css
  src/components/Layout.jsx
  src/components/Login.js
  src/components/Prediction.jsx
  src/components/SentimentChart.jsx
  src/components/Signup.js
  src/components/StockList.jsx
  src/components/StockList.module.css
  src/components/Stockdata.jsx
  src/components/ThemeContext.js
  src/components/ThemeDebug.jsx
  src/components/ThemeToggle.css
  src/components/ThemeToggle.jsx
  src/components/Watchlist.jsx
  src/components/firebase.js
  src/styles/global.css
  start-dev.js
  suppress-webpack-warnings.js
Labels: enhancement, Level 3, status: Approved, OSCI

#183 Fix: Profile dropdown closes smoothly and on navigation
  src/components/Header.css
  src/components/Header.jsx
Labels: enhancement, GSSoC'25, Level 1, status: Approved

#192 feat(auth):Disable paste on registration password fields
  src/components/Signup.js
Labels: bug, GSSoC'25, Level 1, status: Approved
