Repository SrigadaAkshayKumar/stock, pull requests merged in 2025-08, with the labels that each got.

#64 Added Watchlist Feature – React + Firebase Firestore
  src/App.js
  src/components/AuthContext.js
  src/components/Header.jsx
  src/components/Login.js
  src/components/StockList.jsx
  src/components/firebase.js
  src/pages/Watchlist.jsx
  src/utils/firebaseWatchlist.js
  src/utils/watchlistManager.js
Labels: Need Review

#69 Refactor: Modular backend with services, routes, and cleaned structure
  app/config.py
  app/routes/stock_routes.py
  app/services/stock_predict.py
  app/services/stock_service.py
  backend/app.py
  backend/data/INFY.NS.csv
  backend/data/RELIANCE.NS.csv
  backend/data/TCS.NS.csv
  generate_csvs.py
  requirements.txt
Labels: enhancement, GSSoC'25, Advanced Level

#86 Enhance the UI/UX ( added icons to navbar elements)
  package-lock.json
  package.json
  src/components/Header.jsx
  src/components/StockList.jsx
Labels: enhancement, GSSoC'25, Beginner (Level 1), status: Approved

#94 Add AI-Powered News Sentiment Analysis
  .gitignore
  backend/app.py
  backend/app/services/sentiment_service.py
  backend/app/services/stock_service.py
  backend/requirements.txt
  package-lock.json
  package.json
  src/App.css
  src/components/SentimentChart.jsx
  src/components/Stockdata.jsx
Labels: enhancement, GSSoC'25, Medium (Level 2), status: Approved

#118 feat: add accessible Back to Top button with throttle, tooltip, and a…
  src/components/About.jsx
  src/components/BackToTopBtn.jsx
  src/components/ContactForm.jsx
  src/components/StockList.jsx
Labels: enhancement, Beginner (Level 1), status: Approved, OSCI'25

#121 Added contact and about on the same page
  src/App.js
  src/components/ContactForm.jsx
Labels: enhancement, Level 1, status: Approved, OSCI'25

#122 Added proper step by step guide in SETUP.md to run the application locally. Added minor changes to README.md
  README.md
  SETUP.md
Labels: documentation, Level 1, status: Approved, OSCI'25

#140 light/dark mode
  src/App.css
  src/App.js
  src/components/About.jsx
  src/components/ContactForm.jsx
  src/components/ContactForm.module.css
  src/components/Footer.css
  src/components/Footer.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/Login.css
  src/components/Signup.css
  src/components/StockList.jsx
  src/components/StockList.module.css
  src/components/ThemeContext.js
  src/components/ThemeToggle.css
  src/components/ThemeToggle.jsx
  src/components/Watchlist.jsx
  src/components/Watchlist.module.css
  src/styles/global.css
  src/styles/theme-toggle.css
Labels: enhancement, Level 3, status: Approved, OSCI'25

#162 Fixed watchlist only working on logged in
  src/App.js
  src/components/Login.css
  src/components/Login.js
  src/components/StockList.jsx
Labels: GSSoC'25, Level 1, status: Approved

#158 Fix authentication bug and update login/signup logic
  SETUP.md
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/AuthContext.js
  src/components/ContactForm.jsx
  src/components/Login.js
  src/components/Signup.js
  src/components/firebase.js
  src/utils/watchlistManager.js
Labels: Need Review
